name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_binaries:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            suffix: linux-x64
            ext: ""
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            suffix: win-x64
            ext: .exe
          - target: x86_64-apple-darwin
            os: macos-latest
            suffix: macos-x64
            ext: ""
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
            suffix: linux-arm
            ext: ""
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            suffix: linux-arm64
            ext: ""
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build Binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --locked --target=${{ matrix.target }}
      - name: Rename Binary
        run: mv target/${{ matrix.target }}/release/webptz${{ matrix.ext }} target/${{ matrix.target }}/release/webptz_${{ matrix.suffix }}${{ matrix.ext }}
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: binary_${{ matrix.target }}
          path: target/${{ matrix.target }}/release/webptz_${{ matrix.suffix }}${{ matrix.ext }}
  draft_release:
    runs-on: ubuntu-latest
    needs: [build_binaries]
    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: List Directory Files
        run: ls -la
        shell: bash
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: WebPTZ ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: |
            webptz_win-x64.exe
            webptz_linux-x64
            webptz_linux-arm
            webptz_linux-arm64
            webptz_macos-x64
